/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;

class AppTest {
    @Test void testJsonFileObject(){
        ArrayList<Quote> quotes= new ArrayList<>();
        try {
            FileReader jsonFile = new FileReader("Abdallah.json");
            quotes = App.dataJsonR(jsonFile);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        assertEquals("George Orwell",quotes.get(2).getAuthor());
    }
}
