/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Random;

class AppTest {
    @Test void TestJsonFileObject(){
        ArrayList<Quote> quotes= new ArrayList<>();
        try {

            FileReader fileReader = new FileReader("src/test/resources/Abdallah.json");
            quotes = App.dataJsonR(fileReader);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        Random random = new Random();
        int randomBookQuotes = random.nextInt(quotes.size());
        String expected =("Quote{" +
                " author='" +  quotes.get(randomBookQuotes).getAuthor() + '\'' +
                ", likes=" + quotes.get(randomBookQuotes).getLikes() +
                ", text='" + quotes.get(randomBookQuotes).getText() + '\'' +
                '}');



        assertEquals(expected,quotes.get(randomBookQuotes).toString());
    }

}

